apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: localhost
  namespace: projectcontour
spec:
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              serviceName: ingressService
              servicePort: 80
